name: photo_organizer_pc
description: "Aplicación de escritorio para organizar fotos del PC y del móvil."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.0.5
  path: ^1.9.1  # versión estable que funciona con Flutter 3.38

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  http: ^1.2.3
  archive: ^3.3.4
  path: ^1.9.0

flutter:
  uses-material-design: true

  assets:
    - assets/adb/windows/
    - assets/adb/linux/
